/*
* @author lovepsone 2019 - 2024
*/

const Lobby = [
    {name: 'Idle_additive', file: './Game/Characters/Animations/Lobby/Idle_additive.psa', conf: './Game/Characters/Animations/Lobby/Idle_additive.config'},
    {name: 'Lobby_back_man01_idle_01', file: './Game/Characters/Animations/Lobby/Lobby_back_man01_idle_01.psa', conf: './Game/Characters/Animations/Lobby/Lobby_back_man01_idle_01.config'},
    {name: 'Lobby_back_man02_idle_01', file: './Game/Characters/Animations/Lobby/Lobby_back_man02_idle_01.psa', conf: './Game/Characters/Animations/Lobby/Lobby_back_man02_idle_01.config'},
    {name: 'Lobby_back_man03_idle_01', file: './Game/Characters/Animations/Lobby/Lobby_back_man03_idle_01.psa', conf: './Game/Characters/Animations/Lobby/Lobby_back_man03_idle_01.config'},
];

const Additive = [
    {name: 'MOB1_M1_CrouchWalk_Relaxed_Additive', file: './Game/Characters/Animations/Additive/MOB1_M1_CrouchWalk_Relaxed_Additive.psa', conf: './Game/Characters/Animations/Additive/MOB1_M1_CrouchWalk_Relaxed_Additive.config'},
];

const InPlace = [
    {name: 'FP_Mob1_fly_Parachute_Open_IP_V2', file: './Game/Characters/Animations/In-Place/FP_Mob1_fly_Parachute_Open_IP_V2.psa', conf:'./Game/Characters/Animations/In-Place/FP_Mob1_fly_Parachute_Open_IP_V2.config'},
    {name: 'FinalizeDeath', file: './Game/Characters/Animations/In-Place/FinalizeDeath.psa', conf:'./Game/Characters/Animations/In-Place/FinalizeDeath.config'},
    {name: 'Lobby_seat_01', file: './Game/Characters/Animations/In-Place/Lobby_seat_01.psa', conf:'./Game/Characters/Animations/In-Place/Lobby_seat_01.config'},
    {name: 'M1_GAZ-69_Driver_Steering_01', file: './Game/Characters/Animations/In-Place/M1_GAZ-69_Driver_Steering_01.psa', conf:'./Game/Characters/Animations/In-Place/M1_GAZ-69_Driver_Steering_01.config'},
    {name: 'M1_GAZ-69_Passenger_01', file: './Game/Characters/Animations/In-Place/M1_GAZ-69_Passenger_01.psa', conf:'./Game/Characters/Animations/In-Place/M1_GAZ-69_Passenger_01.config'},
    {name: 'MOB1_HitReaction_Back_Loop_01', file: './Game/Characters/Animations/In-Place/MOB1_HitReaction_Back_Loop_01.psa', conf:'./Game/Characters/Animations/In-Place/MOB1_HitReaction_Back_Loop_01.config'},
    {name: 'MOB1_HitReaction_Front_Loop_01', file: './Game/Characters/Animations/In-Place/MOB1_HitReaction_Front_Loop_01.psa', conf:'./Game/Characters/Animations/In-Place/MOB1_HitReaction_Front_Loop_01.config'},
    {name: 'MOB1_HitReaction_Left_Loop_01', file: './Game/Characters/Animations/In-Place/MOB1_HitReaction_Left_Loop_01.psa', conf:'./Game/Characters/Animations/In-Place/MOB1_HitReaction_Left_Loop_01.config'},
    {name: 'MOB1_HitReaction_Pose', file: './Game/Characters/Animations/In-Place/MOB1_HitReaction_Pose.psa', conf:'./Game/Characters/Animations/In-Place/MOB1_HitReaction_Pose.config'},
    {name: 'MOB1_HitReaction_Right_Loop_01', file: './Game/Characters/Animations/In-Place/MOB1_HitReaction_Right_Loop_01.psa', conf:'./Game/Characters/Animations/In-Place/MOB1_HitReaction_Right_Loop_01.config'},
    {name: 'MOB1_M1_3P_Explosive_Idle_Pose_01', file: './Game/Characters/Animations/In-Place/MOB1_M1_3P_Explosive_Idle_Pose_01.psa', conf:'./Game/Characters/Animations/In-Place/MOB1_M1_3P_Explosive_Idle_Pose_01.config'},
    {name: 'MOB1_M1_3P_Explosive_Stand_Idle_01', file: './Game/Characters/Animations/In-Place/MOB1_M1_3P_Explosive_Stand_Idle_01.psa', conf:'./Game/Characters/Animations/In-Place/MOB1_M1_3P_Explosive_Stand_Idle_01.config'},
    {name: 'MOB1_M1_3P_Explosive_Throw_01', file: './Game/Characters/Animations/In-Place/MOB1_M1_3P_Explosive_Throw_01.psa', conf:'./Game/Characters/Animations/In-Place/MOB1_M1_3P_Explosive_Throw_01.config'},
    {name: 'MOB1_M1_3P_Explosive_Use_01', file: './Game/Characters/Animations/In-Place/MOB1_M1_3P_Explosive_Use_01.psa', conf:'./Game/Characters/Animations/In-Place/MOB1_M1_3P_Explosive_Use_01.config'},
    {name: 'MOB1_M1_CrouchWalk_Relaxed_B_Loop_IP', file: './Game/Characters/Animations/In-Place/MOB1_M1_CrouchWalk_Relaxed_B_Loop_IP.psa', conf:'./Game/Characters/Animations/In-Place/MOB1_M1_CrouchWalk_Relaxed_B_Loop_IP.config'},
    {name: 'MOB1_M1_CrouchWalk_Relaxed_B_To_Crouch_Relaxed_IP', file: './Game/Characters/Animations/In-Place/MOB1_M1_CrouchWalk_Relaxed_B_To_Crouch_Relaxed_IP.psa', conf:'./Game/Characters/Animations/In-Place/MOB1_M1_CrouchWalk_Relaxed_B_To_Crouch_Relaxed_IP.config'},
    {name: 'MOB1_M1_CrouchWalk_Relaxed_F_Loop_IP', file: './Game/Characters/Animations/In-Place/MOB1_M1_CrouchWalk_Relaxed_F_Loop_IP.psa', conf:'./Game/Characters/Animations/In-Place/MOB1_M1_CrouchWalk_Relaxed_F_Loop_IP.config'},
    {name: 'MOB1_M1_CrouchWalk_Relaxed_F_To_Crouch_Relaxed_IP', file: './Game/Characters/Animations/In-Place/MOB1_M1_CrouchWalk_Relaxed_F_To_Crouch_Relaxed_IP.psa', conf:'./Game/Characters/Animations/In-Place/MOB1_M1_CrouchWalk_Relaxed_F_To_Crouch_Relaxed_IP.config'},
    {name: 'MOB1_M1_CrouchWalk_Relaxed_L_Loop_IP', file: './Game/Characters/Animations/In-Place/MOB1_M1_CrouchWalk_Relaxed_L_Loop_IP.psa', conf:'./Game/Characters/Animations/In-Place/MOB1_M1_CrouchWalk_Relaxed_L_Loop_IP.config'},
    {name: 'MOB1_M1_CrouchWalk_Relaxed_L_To_Crouch_Relaxed_IP', file: './Game/Characters/Animations/In-Place/MOB1_M1_CrouchWalk_Relaxed_L_To_Crouch_Relaxed_IP.psa', conf:'./Game/Characters/Animations/In-Place/MOB1_M1_CrouchWalk_Relaxed_L_To_Crouch_Relaxed_IP.config'},
    {name: 'MOB1_M1_CrouchWalk_Relaxed_R_Loop_IP', file: './Game/Characters/Animations/In-Place/MOB1_M1_CrouchWalk_Relaxed_R_Loop_IP.psa', conf:'./Game/Characters/Animations/In-Place/MOB1_M1_CrouchWalk_Relaxed_R_Loop_IP.config'},
    {name: 'MOB1_M1_Crouch_Idle_IP_Pose', file: './Game/Characters/Animations/In-Place/MOB1_M1_Crouch_Idle_IP_Pose.psa', conf:'./Game/Characters/Animations/In-Place/MOB1_M1_Crouch_Idle_IP_Pose.config'},
    {name: 'MOB1_M1_Crouch_Relaxed_R_To_CrouchWalk_Relaxed_IP', file: './Game/Characters/Animations/In-Place/MOB1_M1_Crouch_Relaxed_R_To_CrouchWalk_Relaxed_IP.psa', conf:'./Game/Characters/Animations/In-Place/MOB1_M1_Crouch_Relaxed_R_To_CrouchWalk_Relaxed_IP.config'},
    {name: 'MOB1_M1_Crouch_Relaxed_To_CrouchWalk_Relaxed_B_IP', file: './Game/Characters/Animations/In-Place/MOB1_M1_Crouch_Relaxed_To_CrouchWalk_Relaxed_B_IP.psa', conf:'./Game/Characters/Animations/In-Place/MOB1_M1_Crouch_Relaxed_To_CrouchWalk_Relaxed_B_IP.config'},
    {name: 'MOB1_M1_Crouch_Relaxed_To_CrouchWalk_Relaxed_F_IP', file: './Game/Characters/Animations/In-Place/MOB1_M1_Crouch_Relaxed_To_CrouchWalk_Relaxed_F_IP.psa', conf:'./Game/Characters/Animations/In-Place/MOB1_M1_Crouch_Relaxed_To_CrouchWalk_Relaxed_F_IP.config'},
    {name: 'MOB1_M1_Crouch_Relaxed_To_CrouchWalk_Relaxed_L_IP', file: './Game/Characters/Animations/In-Place/MOB1_M1_Crouch_Relaxed_To_CrouchWalk_Relaxed_L_IP.psa', conf:'./Game/Characters/Animations/In-Place/MOB1_M1_Crouch_Relaxed_To_CrouchWalk_Relaxed_L_IP.config'},
    {name: 'MOB1_M1_Crouch_Relaxed_To_CrouchWalk_Relaxed_R_IP', file: './Game/Characters/Animations/In-Place/MOB1_M1_Crouch_Relaxed_To_CrouchWalk_Relaxed_R_IP.psa', conf:'./Game/Characters/Animations/In-Place/MOB1_M1_Crouch_Relaxed_To_CrouchWalk_Relaxed_R_IP.config'},
    {name: 'MOB1_M1_Explosive_Prethrow_Idle_01', file: './Game/Characters/Animations/In-Place/MOB1_M1_Explosive_Prethrow_Idle_01.psa', conf:'./Game/Characters/Animations/In-Place/MOB1_M1_Explosive_Prethrow_Idle_01.config'},
    {name: 'MOB1_M1_Jog_JumpEnd_01', file: './Game/Characters/Animations/In-Place/MOB1_M1_Jog_JumpEnd_01.psa', conf:'./Game/Characters/Animations/In-Place/MOB1_M1_Jog_JumpEnd_01.config'},
    {name: 'MOB1_M1_Jog_Jump_InAir_01', file: './Game/Characters/Animations/In-Place/MOB1_M1_Jog_Jump_InAir_01.psa', conf:'./Game/Characters/Animations/In-Place/MOB1_M1_Jog_Jump_InAir_01.config'},
    {name: 'MOB1_M1_Jog_L_CIR_IP', file: './Game/Characters/Animations/In-Place/MOB1_M1_Jog_L_CIR_IP.psa', conf:'./Game/Characters/Animations/In-Place/MOB1_M1_Jog_L_CIR_IP.config'},
    {name: 'MOB1_M1_Jog_R_CIR_IP', file: './Game/Characters/Animations/In-Place/MOB1_M1_Jog_R_CIR_IP.psa', conf:'./Game/Characters/Animations/In-Place/MOB1_M1_Jog_R_CIR_IP.config'},
    {name: 'MOB1_M1_Jog_Relaxed_B_Loop_IP', file: './Game/Characters/Animations/In-Place/MOB1_M1_Jog_Relaxed_B_Loop_IP.psa', conf:'./Game/Characters/Animations/In-Place/MOB1_M1_Jog_Relaxed_B_Loop_IP.config'},
    {name: 'MOB1_M1_Jog_Relaxed_B_To_Stand_Relaxed_IP', file: './Game/Characters/Animations/In-Place/MOB1_M1_Jog_Relaxed_B_To_Stand_Relaxed_IP.psa', conf:'./Game/Characters/Animations/In-Place/MOB1_M1_Jog_Relaxed_B_To_Stand_Relaxed_IP.config'},
    {name: 'MOB1_M1_Jog_Relaxed_F_Loop_IP', file: './Game/Characters/Animations/In-Place/MOB1_M1_Jog_Relaxed_F_Loop_IP.psa', conf:'./Game/Characters/Animations/In-Place/MOB1_M1_Jog_Relaxed_F_Loop_IP.config'},
    {name: 'MOB1_M1_Jog_Relaxed_F_To_Stand_Relaxed_IP', file: './Game/Characters/Animations/In-Place/MOB1_M1_Jog_Relaxed_F_To_Stand_Relaxed_IP.psa', conf:'./Game/Characters/Animations/In-Place/MOB1_M1_Jog_Relaxed_F_To_Stand_Relaxed_IP.config'},
    {name: 'MOB1_M1_Jog_Relaxed_L_Loop_IP', file: './Game/Characters/Animations/In-Place/MOB1_M1_Jog_Relaxed_L_Loop_IP.psa', conf:'./Game/Characters/Animations/In-Place/MOB1_M1_Jog_Relaxed_L_Loop_IP.config'},
    {name: 'MOB1_M1_Jog_Relaxed_L_To_Stand_Relaxed_IP', file: './Game/Characters/Animations/In-Place/MOB1_M1_Jog_Relaxed_L_To_Stand_Relaxed_IP.psa', conf:'./Game/Characters/Animations/In-Place/MOB1_M1_Jog_Relaxed_L_To_Stand_Relaxed_IP.config'},
    {name: 'MOB1_M1_Jog_Relaxed_R_Loop_IP', file: './Game/Characters/Animations/In-Place/MOB1_M1_Jog_Relaxed_R_Loop_IP.psa', conf:'./Game/Characters/Animations/In-Place/MOB1_M1_Jog_Relaxed_R_Loop_IP.config'},
    {name: 'MOB1_M1_Jog_Relaxed_R_To_Stand_Relaxed_IP', file: './Game/Characters/Animations/In-Place/MOB1_M1_Jog_Relaxed_R_To_Stand_Relaxed_IP.psa', conf:'./Game/Characters/Animations/In-Place/MOB1_M1_Jog_Relaxed_R_To_Stand_Relaxed_IP.config'},
    {name: 'MOB1_M1_Jog_to_Jump_01', file: './Game/Characters/Animations/In-Place/MOB1_M1_Jog_to_Jump_01.psa', conf:'./Game/Characters/Animations/In-Place/MOB1_M1_Jog_to_Jump_01.config'},
    {name: 'MOB1_M1_Jump_Fall_01', file: './Game/Characters/Animations/In-Place/MOB1_M1_Jump_Fall_01.psa', conf:'./Game/Characters/Animations/In-Place/MOB1_M1_Jump_Fall_01.config'},
    {name: 'MOB1_M1_Jump_InAir01', file: './Game/Characters/Animations/In-Place/MOB1_M1_Jump_InAir01.psa', conf:'./Game/Characters/Animations/In-Place/MOB1_M1_Jump_InAir01.config'},
    {name: 'MOB1_M1_Run_F_IP', file: './Game/Characters/Animations/In-Place/MOB1_M1_Run_F_IP.psa', conf:'./Game/Characters/Animations/In-Place/MOB1_M1_Run_F_IP.config'},
    {name: 'MOB1_M1_Run_L_CIR_IP', file: './Game/Characters/Animations/In-Place/MOB1_M1_Run_L_CIR_IP.psa', conf:'./Game/Characters/Animations/In-Place/MOB1_M1_Run_L_CIR_IP.config'},
    {name: 'MOB1_M1_Run_R_CIR_IP', file: './Game/Characters/Animations/In-Place/MOB1_M1_Run_R_CIR_IP.psa', conf:'./Game/Characters/Animations/In-Place/MOB1_M1_Run_R_CIR_IP.config'},
    {name: 'MOB1_M1_Sprint_Relaxed_F_Loop_IP', file: './Game/Characters/Animations/In-Place/MOB1_M1_Sprint_Relaxed_F_Loop_IP.psa', conf:'./Game/Characters/Animations/In-Place/MOB1_M1_Sprint_Relaxed_F_Loop_IP.config'},
    {name: 'MOB1_M1_Sprint_Relaxed_L_Loop_IP', file: './Game/Characters/Animations/In-Place/MOB1_M1_Sprint_Relaxed_L_Loop_IP.psa', conf:'./Game/Characters/Animations/In-Place/MOB1_M1_Sprint_Relaxed_L_Loop_IP.config'},
    {name: 'MOB1_M1_Sprint_Relaxed_R_Loop_IP', file: './Game/Characters/Animations/In-Place/MOB1_M1_Sprint_Relaxed_R_Loop_IP.psa', conf:'./Game/Characters/Animations/In-Place/MOB1_M1_Sprint_Relaxed_R_Loop_IP.config'},
    {name: 'MOB1_M1_Stand_Idle_IP_Pose', file: './Game/Characters/Animations/In-Place/MOB1_M1_Stand_Idle_IP_Pose.psa', conf:'./Game/Characters/Animations/In-Place/MOB1_M1_Stand_Idle_IP_Pose.config'},
    {name: 'MOB1_M1_Stand_Relaxed_Idle_IP', file: './Game/Characters/Animations/In-Place/MOB1_M1_Stand_Relaxed_Idle_IP.psa', conf:'./Game/Characters/Animations/In-Place/MOB1_M1_Stand_Relaxed_Idle_IP.config'},
    {name: 'MOB1_M1_Stand_Relaxed_L45_IP', file: './Game/Characters/Animations/In-Place/MOB1_M1_Stand_Relaxed_L45_IP.psa', conf:'./Game/Characters/Animations/In-Place/MOB1_M1_Stand_Relaxed_L45_IP.config'},
    {name: 'MOB1_M1_Stand_Relaxed_Look_Center', file: './Game/Characters/Animations/In-Place/MOB1_M1_Stand_Relaxed_Look_Center.psa', conf:'./Game/Characters/Animations/In-Place/MOB1_M1_Stand_Relaxed_Look_Center.config'},
    {name: 'MOB1_M1_Stand_Relaxed_R_45_IP', file: './Game/Characters/Animations/In-Place/MOB1_M1_Stand_Relaxed_R_45_IP.psa', conf:'./Game/Characters/Animations/In-Place/MOB1_M1_Stand_Relaxed_R_45_IP.config'},
    {name: 'MOB1_M1_Stand_Relaxed_To_Jog_Relaxed_B_IP', file: './Game/Characters/Animations/In-Place/MOB1_M1_Stand_Relaxed_To_Jog_Relaxed_B_IP.psa', conf:'./Game/Characters/Animations/In-Place/MOB1_M1_Stand_Relaxed_To_Jog_Relaxed_B_IP.config'},
    {name: 'MOB1_M1_Stand_Relaxed_To_Jog_Relaxed_F_IP', file: './Game/Characters/Animations/In-Place/MOB1_M1_Stand_Relaxed_To_Jog_Relaxed_F_IP.psa', conf:'./Game/Characters/Animations/In-Place/MOB1_M1_Stand_Relaxed_To_Jog_Relaxed_F_IP.config'},
    {name: 'MOB1_M1_Stand_Relaxed_To_Jog_Relaxed_L_IP', file: './Game/Characters/Animations/In-Place/MOB1_M1_Stand_Relaxed_To_Jog_Relaxed_L_IP.psa', conf:'./Game/Characters/Animations/In-Place/MOB1_M1_Stand_Relaxed_To_Jog_Relaxed_L_IP.config'},
    {name: 'MOB1_M1_Stand_Relaxed_To_Jog_Relaxed_R_IP', file: './Game/Characters/Animations/In-Place/MOB1_M1_Stand_Relaxed_To_Jog_Relaxed_R_IP.psa', conf:'./Game/Characters/Animations/In-Place/MOB1_M1_Stand_Relaxed_To_Jog_Relaxed_R_IP.config'},
    {name: 'MOB1_M1_Stand_Relaxed_To_Sprint_Relaxed_F_IP', file: './Game/Characters/Animations/In-Place/MOB1_M1_Stand_Relaxed_To_Sprint_Relaxed_F_IP.psa', conf:'./Game/Characters/Animations/In-Place/MOB1_M1_Stand_Relaxed_To_Sprint_Relaxed_F_IP.config'},
    {name: 'MOB1_M1_Stand_Relaxed_To_Sprint_Relaxed_L_IP', file: './Game/Characters/Animations/In-Place/MOB1_M1_Stand_Relaxed_To_Sprint_Relaxed_L_IP.psa', conf:'./Game/Characters/Animations/In-Place/MOB1_M1_Stand_Relaxed_To_Sprint_Relaxed_L_IP.config'},
    {name: 'MOB1_M1_Stand_Relaxed_To_Sprint_Relaxed_R_IP', file: './Game/Characters/Animations/In-Place/MOB1_M1_Stand_Relaxed_To_Sprint_Relaxed_R_IP.psa', conf:'./Game/Characters/Animations/In-Place/MOB1_M1_Stand_Relaxed_To_Sprint_Relaxed_R_IP.config'},
    {name: 'MOB1_M1_Stand_Relaxed_To_Walk_Relaxed_B_IP', file: './Game/Characters/Animations/In-Place/MOB1_M1_Stand_Relaxed_To_Walk_Relaxed_B_IP.psa', conf:'./Game/Characters/Animations/In-Place/MOB1_M1_Stand_Relaxed_To_Walk_Relaxed_B_IP.config'},
    {name: 'MOB1_M1_Stand_Relaxed_To_Walk_Relaxed_F_IP', file: './Game/Characters/Animations/In-Place/MOB1_M1_Stand_Relaxed_To_Walk_Relaxed_F_IP.psa', conf:'./Game/Characters/Animations/In-Place/MOB1_M1_Stand_Relaxed_To_Walk_Relaxed_F_IP.config'},
    {name: 'MOB1_M1_Stand_Relaxed_To_Walk_Relaxed_L_IP', file: './Game/Characters/Animations/In-Place/MOB1_M1_Stand_Relaxed_To_Walk_Relaxed_L_IP.psa', conf:'./Game/Characters/Animations/In-Place/MOB1_M1_Stand_Relaxed_To_Walk_Relaxed_L_IP.config'},
    {name: 'MOB1_M1_Stand_Relaxed_To_Walk_Relaxed_R_IP', file: './Game/Characters/Animations/In-Place/MOB1_M1_Stand_Relaxed_To_Walk_Relaxed_R_IP.psa', conf:'./Game/Characters/Animations/In-Place/MOB1_M1_Stand_Relaxed_To_Walk_Relaxed_R_IP.config'},
    {name: 'MOB1_M1_Stand_to_Jump_01', file: './Game/Characters/Animations/In-Place/MOB1_M1_Stand_to_Jump_01.psa', conf:'./Game/Characters/Animations/In-Place/MOB1_M1_Stand_to_Jump_01.config'},
    {name: 'MOB1_M1_Walk_Relaxed_B_Loop_IP', file: './Game/Characters/Animations/In-Place/MOB1_M1_Walk_Relaxed_B_Loop_IP.psa', conf:'./Game/Characters/Animations/In-Place/MOB1_M1_Walk_Relaxed_B_Loop_IP.config'},
    {name: 'MOB1_M1_Walk_Relaxed_F_Loop_IP', file: './Game/Characters/Animations/In-Place/MOB1_M1_Walk_Relaxed_F_Loop_IP.psa', conf:'./Game/Characters/Animations/In-Place/MOB1_M1_Walk_Relaxed_F_Loop_IP.config'},
    {name: 'MOB1_M1_Walk_Relaxed_L_Loop_IP', file: './Game/Characters/Animations/In-Place/MOB1_M1_Walk_Relaxed_L_Loop_IP.psa', conf:'./Game/Characters/Animations/In-Place/MOB1_M1_Walk_Relaxed_L_Loop_IP.config'},
    {name: 'MOB1_M1_Walk_Relaxed_R_Loop_IP', file: './Game/Characters/Animations/In-Place/MOB1_M1_Walk_Relaxed_R_Loop_IP.psa', conf:'./Game/Characters/Animations/In-Place/MOB1_M1_Walk_Relaxed_R_Loop_IP.config'},
    {name: 'Male_Jab_Loop_01_IP', file: './Game/Characters/Animations/In-Place/Male_Jab_Loop_01_IP.psa', conf:'./Game/Characters/Animations/In-Place/Male_Jab_Loop_01_IP.config'},
    {name: 'Male_Jab_Loop_01_Idle_IP', file: './Game/Characters/Animations/In-Place/Male_Jab_Loop_01_Idle_IP.psa', conf:'./Game/Characters/Animations/In-Place/Male_Jab_Loop_01_Idle_IP.config'},
    {name: 'Male_Jogging_Consumable', file: './Game/Characters/Animations/In-Place/Male_Jogging_Consumable.psa', conf:'./Game/Characters/Animations/In-Place/Male_Jogging_Consumable.config'},
    {name: 'Male_Jogging_Pistol', file: './Game/Characters/Animations/In-Place/Male_Jogging_Pistol.psa', conf:'./Game/Characters/Animations/In-Place/Male_Jogging_Pistol.config'},
    {name: 'Male_Stand_Idle_Pistol', file: './Game/Characters/Animations/In-Place/Male_Stand_Idle_Pistol.psa', conf:'./Game/Characters/Animations/In-Place/Male_Stand_Idle_Pistol.config'},
    {name: 'Mob1_landing_01', file: './Game/Characters/Animations/In-Place/Mob1_landing_01.psa', conf:'./Game/Characters/Animations/In-Place/Mob1_landing_01.config'},
    {name: 'Revive_Loop_IP_01', file: './Game/Characters/Animations/In-Place/Revive_Loop_IP_01.psa', conf:'./Game/Characters/Animations/In-Place/Revive_Loop_IP_01.config'},
    {name: 'Rope_Use_Loop_IP_01', file: './Game/Characters/Animations/In-Place/Rope_Use_Loop_IP_01.psa', conf:'./Game/Characters/Animations/In-Place/Rope_Use_Loop_IP_01.config'},
    {name: 'TPS_Body_Medkit_Use_01', file: './Game/Characters/Animations/In-Place/TPS_Body_Medkit_Use_01.psa', conf:'./Game/Characters/Animations/In-Place/TPS_Body_Medkit_Use_01.config'},
    {name: 'TPS_Booster_01_Use', file: './Game/Characters/Animations/In-Place/TPS_Booster_01_Use.psa', conf:'./Game/Characters/Animations/In-Place/TPS_Booster_01_Use.config'},
    {name: 'TPS_Drink_01_Use', file: './Game/Characters/Animations/In-Place/TPS_Drink_01_Use.psa', conf:'./Game/Characters/Animations/In-Place/TPS_Drink_01_Use.config'},
    {name: 'TPS_Food_01_Use', file: './Game/Characters/Animations/In-Place/TPS_Food_01_Use.psa', conf:'./Game/Characters/Animations/In-Place/TPS_Food_01_Use.config'},
    {name: 'TPS_MOB_EvacuationLiftUp_Pose_01', file: './Game/Characters/Animations/In-Place/TPS_MOB_EvacuationLiftUp_Pose_01.psa', conf:'./Game/Characters/Animations/In-Place/TPS_MOB_EvacuationLiftUp_Pose_01.config'},
    {name: 'TPS_Painkiller_use_01', file: './Game/Characters/Animations/In-Place/TPS_Painkiller_use_01.psa', conf:'./Game/Characters/Animations/In-Place/TPS_Painkiller_use_01.config'},
    {name: 'TPS_Vodka_01_Use', file: './Game/Characters/Animations/In-Place/TPS_Vodka_01_Use.psa', conf:'./Game/Characters/Animations/In-Place/TPS_Vodka_01_Use.config'},
    {name: 'TPS_W2_EvacuationLiftUp_Pose_01', file: './Game/Characters/Animations/In-Place/TPS_W2_EvacuationLiftUp_Pose_01.psa', conf:'./Game/Characters/Animations/In-Place/TPS_W2_EvacuationLiftUp_Pose_01.config'},
    {name: 'Use_Door', file: './Game/Characters/Animations/In-Place/Use_Door.psa', conf:'./Game/Characters/Animations/In-Place/Use_Door.config'},
    {name: 'W2_Axe_Sprint_Override_Pose_01', file: './Game/Characters/Animations/In-Place/W2_Axe_Sprint_Override_Pose_01.psa', conf:'./Game/Characters/Animations/In-Place/W2_Axe_Sprint_Override_Pose_01.config'},
    {name: 'W2_Axe_melee_attack_03', file: './Game/Characters/Animations/In-Place/W2_Axe_melee_attack_03.psa', conf:'./Game/Characters/Animations/In-Place/W2_Axe_melee_attack_03.config'},
    {name: 'W2_HitReaction_Front_Loop_01', file: './Game/Characters/Animations/In-Place/W2_HitReaction_Front_Loop_01.psa', conf:'./Game/Characters/Animations/In-Place/W2_HitReaction_Front_Loop_01.config'},
    {name: 'W2_HitReaction_Left_Loop_01', file: './Game/Characters/Animations/In-Place/W2_HitReaction_Left_Loop_01.psa', conf:'./Game/Characters/Animations/In-Place/W2_HitReaction_Left_Loop_01.config'},
    {name: 'W2_HitReaction_Pose', file: './Game/Characters/Animations/In-Place/W2_HitReaction_Pose.psa', conf:'./Game/Characters/Animations/In-Place/W2_HitReaction_Pose.config'},
    {name: 'W2_Jog_Aim_F_Jump_IP', file: './Game/Characters/Animations/In-Place/W2_Jog_Aim_F_Jump_IP.psa', conf:'./Game/Characters/Animations/In-Place/W2_Jog_Aim_F_Jump_IP.config'},
    {name: 'W2_Jog_Aim_L_CIR_Loop_IP', file: './Game/Characters/Animations/In-Place/W2_Jog_Aim_L_CIR_Loop_IP.psa', conf:'./Game/Characters/Animations/In-Place/W2_Jog_Aim_L_CIR_Loop_IP.config'},
    {name: 'W2_Jog_Aim_R_CIR_Loop_IP', file: './Game/Characters/Animations/In-Place/W2_Jog_Aim_R_CIR_Loop_IP.psa', conf:'./Game/Characters/Animations/In-Place/W2_Jog_Aim_R_CIR_Loop_IP.config'},
    {name: 'W2_Lie_Idle_IP', file: './Game/Characters/Animations/In-Place/W2_Lie_Idle_IP.psa', conf:'./Game/Characters/Animations/In-Place/W2_Lie_Idle_IP.config'},
    {name: 'W2_M1_CrouchWalk_Aim_B_Loop_IP', file: './Game/Characters/Animations/In-Place/W2_M1_CrouchWalk_Aim_B_Loop_IP.psa', conf:'./Game/Characters/Animations/In-Place/W2_M1_CrouchWalk_Aim_B_Loop_IP.config'},
    {name: 'W2_M1_CrouchWalk_Aim_B_To_Crouch_Aim_Idle_IP', file: './Game/Characters/Animations/In-Place/W2_M1_CrouchWalk_Aim_B_To_Crouch_Aim_Idle_IP.psa', conf:'./Game/Characters/Animations/In-Place/W2_M1_CrouchWalk_Aim_B_To_Crouch_Aim_Idle_IP.config'},
    {name: 'W2_M1_CrouchWalk_Aim_F_Loop_IP', file: './Game/Characters/Animations/In-Place/W2_M1_CrouchWalk_Aim_F_Loop_IP.psa', conf:'./Game/Characters/Animations/In-Place/W2_M1_CrouchWalk_Aim_F_Loop_IP.config'},
    {name: 'W2_M1_CrouchWalk_Aim_F_To_Crouch_Aim_IP', file: './Game/Characters/Animations/In-Place/W2_M1_CrouchWalk_Aim_F_To_Crouch_Aim_IP.psa', conf:'./Game/Characters/Animations/In-Place/W2_M1_CrouchWalk_Aim_F_To_Crouch_Aim_IP.config'},
    {name: 'W2_M1_CrouchWalk_Aim_L_Loop_IP', file: './Game/Characters/Animations/In-Place/W2_M1_CrouchWalk_Aim_L_Loop_IP.psa', conf:'./Game/Characters/Animations/In-Place/W2_M1_CrouchWalk_Aim_L_Loop_IP.config'},
    {name: 'W2_M1_CrouchWalk_Aim_R_Loop_IP', file: './Game/Characters/Animations/In-Place/W2_M1_CrouchWalk_Aim_R_Loop_IP.psa', conf:'./Game/Characters/Animations/In-Place/W2_M1_CrouchWalk_Aim_R_Loop_IP.config'},
    {name: 'W2_M1_CrouchWalk_Aim_To_Crouch_Aim_Idle_L_IP', file: './Game/Characters/Animations/In-Place/W2_M1_CrouchWalk_Aim_To_Crouch_Aim_Idle_L_IP.psa', conf:'./Game/Characters/Animations/In-Place/W2_M1_CrouchWalk_Aim_To_Crouch_Aim_Idle_L_IP.config'},
    {name: 'W2_M1_CrouchWalk_Aim_To_Crouch_Aim_Idle_R_IP', file: './Game/Characters/Animations/In-Place/W2_M1_CrouchWalk_Aim_To_Crouch_Aim_Idle_R_IP.psa', conf:'./Game/Characters/Animations/In-Place/W2_M1_CrouchWalk_Aim_To_Crouch_Aim_Idle_R_IP.config'},
    {name: 'W2_M1_Crouch_Aim_F_To_CrouchWalk_Aim_IP', file: './Game/Characters/Animations/In-Place/W2_M1_Crouch_Aim_F_To_CrouchWalk_Aim_IP.psa', conf:'./Game/Characters/Animations/In-Place/W2_M1_Crouch_Aim_F_To_CrouchWalk_Aim_IP.config'},
    {name: 'W2_M1_Crouch_Aim_Idle_IP_Pose', file: './Game/Characters/Animations/In-Place/W2_M1_Crouch_Aim_Idle_IP_Pose.psa', conf:'./Game/Characters/Animations/In-Place/W2_M1_Crouch_Aim_Idle_IP_Pose.config'},
    {name: 'W2_M1_Crouch_Aim_Idle_To_CrouchWalk_Aim_B_IP', file: './Game/Characters/Animations/In-Place/W2_M1_Crouch_Aim_Idle_To_CrouchWalk_Aim_B_IP.psa', conf:'./Game/Characters/Animations/In-Place/W2_M1_Crouch_Aim_Idle_To_CrouchWalk_Aim_B_IP.config'},
    {name: 'W2_M1_Crouch_Aim_Idle_To_CrouchWalk_Aim_L_IP', file: './Game/Characters/Animations/In-Place/W2_M1_Crouch_Aim_Idle_To_CrouchWalk_Aim_L_IP.psa', conf:'./Game/Characters/Animations/In-Place/W2_M1_Crouch_Aim_Idle_To_CrouchWalk_Aim_L_IP.config'},
    {name: 'W2_M1_Crouch_Aim_Idle_To_CrouchWalk_Aim_R_IP', file: './Game/Characters/Animations/In-Place/W2_M1_Crouch_Aim_Idle_To_CrouchWalk_Aim_R_IP.psa', conf:'./Game/Characters/Animations/In-Place/W2_M1_Crouch_Aim_Idle_To_CrouchWalk_Aim_R_IP.config'},
    {name: 'W2_M1_Crouch_F_Aim_IP', file: './Game/Characters/Animations/In-Place/W2_M1_Crouch_F_Aim_IP.psa', conf:'./Game/Characters/Animations/In-Place/W2_M1_Crouch_F_Aim_IP.config'},
    {name: 'W2_M1_HitReaction_Back_Loop_01', file: './Game/Characters/Animations/In-Place/W2_M1_HitReaction_Back_Loop_01.psa', conf:'./Game/Characters/Animations/In-Place/W2_M1_HitReaction_Back_Loop_01.config'},
    {name: 'W2_M1_HitReaction_Right_Loop_01', file: './Game/Characters/Animations/In-Place/W2_M1_HitReaction_Right_Loop_01.psa', conf:'./Game/Characters/Animations/In-Place/W2_M1_HitReaction_Right_Loop_01.config'},
    {name: 'W2_M1_Jog_Aim_B_Loop_IP', file: './Game/Characters/Animations/In-Place/W2_M1_Jog_Aim_B_Loop_IP.psa', conf:'./Game/Characters/Animations/In-Place/W2_M1_Jog_Aim_B_Loop_IP.config'},
    {name: 'W2_M1_Jog_Aim_F_Loop_IP', file: './Game/Characters/Animations/In-Place/W2_M1_Jog_Aim_F_Loop_IP.psa', conf:'./Game/Characters/Animations/In-Place/W2_M1_Jog_Aim_F_Loop_IP.config'},
    {name: 'W2_M1_Jog_Aim_L_Loop_IP', file: './Game/Characters/Animations/In-Place/W2_M1_Jog_Aim_L_Loop_IP.psa', conf:'./Game/Characters/Animations/In-Place/W2_M1_Jog_Aim_L_Loop_IP.config'},
    {name: 'W2_M1_Jog_Aim_R_Loop_IP', file: './Game/Characters/Animations/In-Place/W2_M1_Jog_Aim_R_Loop_IP.psa', conf:'./Game/Characters/Animations/In-Place/W2_M1_Jog_Aim_R_Loop_IP.config'},
    {name: 'W2_M1_Jog_Aim_To_Stand_Aim_B_IP', file: './Game/Characters/Animations/In-Place/W2_M1_Jog_Aim_To_Stand_Aim_B_IP.psa', conf:'./Game/Characters/Animations/In-Place/W2_M1_Jog_Aim_To_Stand_Aim_B_IP.config'},
    {name: 'W2_M1_Jog_Aim_To_Stand_Aim_F_IP', file: './Game/Characters/Animations/In-Place/W2_M1_Jog_Aim_To_Stand_Aim_F_IP.psa', conf:'./Game/Characters/Animations/In-Place/W2_M1_Jog_Aim_To_Stand_Aim_F_IP.config'},
    {name: 'W2_M1_Jog_Aim_To_Stand_Aim_L_IP', file: './Game/Characters/Animations/In-Place/W2_M1_Jog_Aim_To_Stand_Aim_L_IP.psa', conf:'./Game/Characters/Animations/In-Place/W2_M1_Jog_Aim_To_Stand_Aim_L_IP.config'},
    {name: 'W2_M1_Jog_Aim_To_Stand_Aim_R_IP', file: './Game/Characters/Animations/In-Place/W2_M1_Jog_Aim_To_Stand_Aim_R_IP.psa', conf:'./Game/Characters/Animations/In-Place/W2_M1_Jog_Aim_To_Stand_Aim_R_IP.config'},
    {name: 'W2_M1_Prone_Aim_BL_Loop_IP', file: './Game/Characters/Animations/In-Place/W2_M1_Prone_Aim_BL_Loop_IP.psa', conf:'./Game/Characters/Animations/In-Place/W2_M1_Prone_Aim_BL_Loop_IP.config'},
    {name: 'W2_M1_Prone_Aim_BR_Loop_IP', file: './Game/Characters/Animations/In-Place/W2_M1_Prone_Aim_BR_Loop_IP.psa', conf:'./Game/Characters/Animations/In-Place/W2_M1_Prone_Aim_BR_Loop_IP.config'},
    {name: 'W2_M1_Prone_Aim_B_Loop_IP', file: './Game/Characters/Animations/In-Place/W2_M1_Prone_Aim_B_Loop_IP.psa', conf:'./Game/Characters/Animations/In-Place/W2_M1_Prone_Aim_B_Loop_IP.config'},
    {name: 'W2_M1_Prone_Aim_FL_Loop_IP', file: './Game/Characters/Animations/In-Place/W2_M1_Prone_Aim_FL_Loop_IP.psa', conf:'./Game/Characters/Animations/In-Place/W2_M1_Prone_Aim_FL_Loop_IP.config'},
    {name: 'W2_M1_Prone_Aim_FR_Loop_IP', file: './Game/Characters/Animations/In-Place/W2_M1_Prone_Aim_FR_Loop_IP.psa', conf:'./Game/Characters/Animations/In-Place/W2_M1_Prone_Aim_FR_Loop_IP.config'},
    {name: 'W2_M1_Prone_Aim_F_Loop_IP', file: './Game/Characters/Animations/In-Place/W2_M1_Prone_Aim_F_Loop_IP.psa', conf:'./Game/Characters/Animations/In-Place/W2_M1_Prone_Aim_F_Loop_IP.config'},
    {name: 'W2_M1_Prone_Aim_L_Loop_IP', file: './Game/Characters/Animations/In-Place/W2_M1_Prone_Aim_L_Loop_IP.psa', conf:'./Game/Characters/Animations/In-Place/W2_M1_Prone_Aim_L_Loop_IP.config'},
    {name: 'W2_M1_Prone_Aim_R_Loop_IP', file: './Game/Characters/Animations/In-Place/W2_M1_Prone_Aim_R_Loop_IP.psa', conf:'./Game/Characters/Animations/In-Place/W2_M1_Prone_Aim_R_Loop_IP.config'},
    {name: 'W2_M1_Prone_Idle', file: './Game/Characters/Animations/In-Place/W2_M1_Prone_Idle.psa', conf:'./Game/Characters/Animations/In-Place/W2_M1_Prone_Idle.config'},
    {name: 'W2_M1_Sprint_Aim_F_Loop_IP', file: './Game/Characters/Animations/In-Place/W2_M1_Sprint_Aim_F_Loop_IP.psa', conf:'./Game/Characters/Animations/In-Place/W2_M1_Sprint_Aim_F_Loop_IP.config'},
    {name: 'W2_M1_Sprint_Aim_L_Loop_IP', file: './Game/Characters/Animations/In-Place/W2_M1_Sprint_Aim_L_Loop_IP.psa', conf:'./Game/Characters/Animations/In-Place/W2_M1_Sprint_Aim_L_Loop_IP.config'},
    {name: 'W2_M1_Sprint_Aim_R_Loop_IP', file: './Game/Characters/Animations/In-Place/W2_M1_Sprint_Aim_R_Loop_IP.psa', conf:'./Game/Characters/Animations/In-Place/W2_M1_Sprint_Aim_R_Loop_IP.config'},
    {name: 'W2_M1_Stand_Aim_IP', file: './Game/Characters/Animations/In-Place/W2_M1_Stand_Aim_IP.psa', conf:'./Game/Characters/Animations/In-Place/W2_M1_Stand_Aim_IP.config'},
    {name: 'W2_M1_Stand_Aim_Idle_IP_Pose', file: './Game/Characters/Animations/In-Place/W2_M1_Stand_Aim_Idle_IP_Pose.psa', conf:'./Game/Characters/Animations/In-Place/W2_M1_Stand_Aim_Idle_IP_Pose.config'},
    {name: 'W2_M1_Stand_Aim_To_Jog_Aim_B_IP', file: './Game/Characters/Animations/In-Place/W2_M1_Stand_Aim_To_Jog_Aim_B_IP.psa', conf:'./Game/Characters/Animations/In-Place/W2_M1_Stand_Aim_To_Jog_Aim_B_IP.config'},
    {name: 'W2_M1_Stand_Aim_To_Jog_Aim_F_IP', file: './Game/Characters/Animations/In-Place/W2_M1_Stand_Aim_To_Jog_Aim_F_IP.psa', conf:'./Game/Characters/Animations/In-Place/W2_M1_Stand_Aim_To_Jog_Aim_F_IP.config'},
    {name: 'W2_M1_Stand_Aim_To_Jog_Aim_L_IP', file: './Game/Characters/Animations/In-Place/W2_M1_Stand_Aim_To_Jog_Aim_L_IP.psa', conf:'./Game/Characters/Animations/In-Place/W2_M1_Stand_Aim_To_Jog_Aim_L_IP.config'},
    {name: 'W2_M1_Stand_Aim_To_Jog_Aim_R_IP', file: './Game/Characters/Animations/In-Place/W2_M1_Stand_Aim_To_Jog_Aim_R_IP.psa', conf:'./Game/Characters/Animations/In-Place/W2_M1_Stand_Aim_To_Jog_Aim_R_IP.config'},
    {name: 'W2_M1_Stand_Aim_To_Sprint_Aim_F_IP', file: './Game/Characters/Animations/In-Place/W2_M1_Stand_Aim_To_Sprint_Aim_F_IP.psa', conf:'./Game/Characters/Animations/In-Place/W2_M1_Stand_Aim_To_Sprint_Aim_F_IP.config'},
    {name: 'W2_M1_Stand_Aim_To_Sprint_Aim_L_IP', file: './Game/Characters/Animations/In-Place/W2_M1_Stand_Aim_To_Sprint_Aim_L_IP.psa', conf:'./Game/Characters/Animations/In-Place/W2_M1_Stand_Aim_To_Sprint_Aim_L_IP.config'},
    {name: 'W2_M1_Stand_Aim_To_Sprint_Aim_R_IP', file: './Game/Characters/Animations/In-Place/W2_M1_Stand_Aim_To_Sprint_Aim_R_IP.psa', conf:'./Game/Characters/Animations/In-Place/W2_M1_Stand_Aim_To_Sprint_Aim_R_IP.config'},
    {name: 'W2_M1_Stand_Aim_To_Walk_Aim_B_IP', file: './Game/Characters/Animations/In-Place/W2_M1_Stand_Aim_To_Walk_Aim_B_IP.psa', conf:'./Game/Characters/Animations/In-Place/W2_M1_Stand_Aim_To_Walk_Aim_B_IP.config'},
    {name: 'W2_M1_Stand_Aim_To_Walk_Aim_F_IP', file: './Game/Characters/Animations/In-Place/W2_M1_Stand_Aim_To_Walk_Aim_F_IP.psa', conf:'./Game/Characters/Animations/In-Place/W2_M1_Stand_Aim_To_Walk_Aim_F_IP.config'},
    {name: 'W2_M1_Stand_Aim_To_Walk_Aim_L_IP', file: './Game/Characters/Animations/In-Place/W2_M1_Stand_Aim_To_Walk_Aim_L_IP.psa', conf:'./Game/Characters/Animations/In-Place/W2_M1_Stand_Aim_To_Walk_Aim_L_IP.config'},
    {name: 'W2_M1_Stand_Aim_To_Walk_Aim_R_IP', file: './Game/Characters/Animations/In-Place/W2_M1_Stand_Aim_To_Walk_Aim_R_IP.psa', conf:'./Game/Characters/Animations/In-Place/W2_M1_Stand_Aim_To_Walk_Aim_R_IP.config'},
    {name: 'W2_M1_Stand_Unholster_01', file: './Game/Characters/Animations/In-Place/W2_M1_Stand_Unholster_01.psa', conf:'./Game/Characters/Animations/In-Place/W2_M1_Stand_Unholster_01.config'},
    {name: 'W2_M1_Walk_Aim_B_Loop_IP', file: './Game/Characters/Animations/In-Place/W2_M1_Walk_Aim_B_Loop_IP.psa', conf:'./Game/Characters/Animations/In-Place/W2_M1_Walk_Aim_B_Loop_IP.config'},
    {name: 'W2_M1_Walk_Aim_F_Loop_IP', file: './Game/Characters/Animations/In-Place/W2_M1_Walk_Aim_F_Loop_IP.psa', conf:'./Game/Characters/Animations/In-Place/W2_M1_Walk_Aim_F_Loop_IP.config'},
    {name: 'W2_M1_Walk_Aim_L_Loop_IP', file: './Game/Characters/Animations/In-Place/W2_M1_Walk_Aim_L_Loop_IP.psa', conf:'./Game/Characters/Animations/In-Place/W2_M1_Walk_Aim_L_Loop_IP.config'},
    {name: 'W2_M1_Walk_Aim_R_Loop_IP', file: './Game/Characters/Animations/In-Place/W2_M1_Walk_Aim_R_Loop_IP.psa', conf:'./Game/Characters/Animations/In-Place/W2_M1_Walk_Aim_R_Loop_IP.config'},
    {name: 'W2_M1_holster_Stand_01', file: './Game/Characters/Animations/In-Place/W2_M1_holster_Stand_01.psa', conf:'./Game/Characters/Animations/In-Place/W2_M1_holster_Stand_01.config'},
    {name: 'W2_Run_L_CIR_Loop_IP', file: './Game/Characters/Animations/In-Place/W2_Run_L_CIR_Loop_IP.psa', conf:'./Game/Characters/Animations/In-Place/W2_Run_L_CIR_Loop_IP.config'},
    {name: 'W2_Run_R_CIR_Loop_IP', file: './Game/Characters/Animations/In-Place/W2_Run_R_CIR_Loop_IP.psa', conf:'./Game/Characters/Animations/In-Place/W2_Run_R_CIR_Loop_IP.config'},
    {name: 'W2_Stand_Aim_Idle_IP', file: './Game/Characters/Animations/In-Place/W2_Stand_Aim_Idle_IP.psa', conf:'./Game/Characters/Animations/In-Place/W2_Stand_Aim_Idle_IP.config'},
    {name: 'W2_Stand_Aim_Idle_v2_IP', file: './Game/Characters/Animations/In-Place/W2_Stand_Aim_Idle_v2_IP.psa', conf:'./Game/Characters/Animations/In-Place/W2_Stand_Aim_Idle_v2_IP.config'},
    {name: 'W2_Stand_Aim_L_45_IP', file: './Game/Characters/Animations/In-Place/W2_Stand_Aim_L_45_IP.psa', conf:'./Game/Characters/Animations/In-Place/W2_Stand_Aim_L_45_IP.config'},
    {name: 'W2_Stand_Aim_R_45_IP', file: './Game/Characters/Animations/In-Place/W2_Stand_Aim_R_45_IP.psa', conf:'./Game/Characters/Animations/In-Place/W2_Stand_Aim_R_45_IP.config'},
    {name: 'W2_Stand_Aim_Reload_IP', file: './Game/Characters/Animations/In-Place/W2_Stand_Aim_Reload_IP.psa', conf:'./Game/Characters/Animations/In-Place/W2_Stand_Aim_Reload_IP.config'},
    {name: 'W2_Stand_Fire_Single_IP', file: './Game/Characters/Animations/In-Place/W2_Stand_Fire_Single_IP.psa', conf:'./Game/Characters/Animations/In-Place/W2_Stand_Fire_Single_IP.config'},
    {name: 'W2_Stand_Relaxed_Death_B_Fly_IP', file: './Game/Characters/Animations/In-Place/W2_Stand_Relaxed_Death_B_Fly_IP.psa', conf:'./Game/Characters/Animations/In-Place/W2_Stand_Relaxed_Death_B_Fly_IP.config'},
    {name: 'W2_landing_01', file: './Game/Characters/Animations/In-Place/W2_landing_01.psa', conf:'./Game/Characters/Animations/In-Place/W2_landing_01.config'},
    {name: 'knockdown_idle_loop_IP_01', file: './Game/Characters/Animations/In-Place/knockdown_idle_loop_IP_01.psa', conf:'./Game/Characters/Animations/In-Place/knockdown_idle_loop_IP_01.config'},
    {name: 'knockdown_to_stand_IP_01', file: './Game/Characters/Animations/In-Place/knockdown_to_stand_IP_01.psa', conf:'./Game/Characters/Animations/In-Place/knockdown_to_stand_IP_01.config'},
    {name: 'stand_to_knockdown_IP_01', file: './Game/Characters/Animations/In-Place/stand_to_knockdown_IP_01.psa', conf:'./Game/Characters/Animations/In-Place/stand_to_knockdown_IP_01.config'}
]

export const ANIMATIONS = {Lobby, Additive, InPlace};
